### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by ghost** [donadigo/elementary-ide#1]
Hello, 

I can't compile your project. 
First : libvala-0.32-dev doesn't exist in apt this day. i had to modify cmake to use the 0.30 version.
Second : 
CMake Error at CMakeLists.txt:26 (include):
  include could not find load file:
    ValaVersion

CMake Error at CMakeLists.txt:27 (ensure_vala_version):
  Unknown CMake command "ensure_vala_version".

-- Configuring incomplete, errors occurred!

Thanks,

**Comment by donadigo** [comment]
Hi, can you tell me what OS are you using first? elementary OS has it's own patches to include up to date vala versions and it has it available in the repos.

About the second issue, it also contains "cmake-elementary" package which has all the needed CMake modules in order to compile apps, though in the next commit I will include them in the project so it won't be needed anymore.

**Comment by ghost** [comment]
I'm using Loki. 

i've tried to add cmake directory, with no luck. as i viewed cmake files in src/ i stop my investigations... 

It would be easier if the cmake-elementary package has been commited, so i'll be waiting the next commit :)

**Comment by donadigo** [comment]
Thanks :) The commit is live and with it the cmake modules are included in the project. I bumped the libvala version to 0.34 as this is the version from os-patches PPA. It did compile for me fine without any additional PPA's and without cmake-elementary package. If it still doesn't compile for you please comment, so I can reopen the issue again. Also please make sure that you have fully updated the system.
